# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: "http://www.rachelkrantz.com"
title: Rachel Krantz
email: 
author: Rachel Krantz
description: > # Rachel Krantz is a software engineer living in Delaware.
baseurl: ""

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/krantzinator
  - title: linkedin
    url: https://www.linkedin.com/in/rachelkrantz
